# Generated by Django 6.1.1 on 2026-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('listing_type', models.CharField(choices=[('website', 'Website'), ('bot', 'Telegram bot'), ('app', 'App')], max_length=20)),
                ('tag', models.CharField(max_length=80)),
                ('price', models.PositiveIntegerField(help_text='Asking price in USD')),
                ('metric', models.CharField(help_text='Headline traction, e.g. 2.4k monthly users', max_length=80)),
                ('description', models.TextField()),
                ('preview_name', models.CharField(blank=True, max_length=80)),
                ('preview_tagline', models.CharField(blank=True, max_length=160)),
                ('visual_class', models.CharField(default='v1', max_length=8)),
                ('visual_label', models.CharField(max_length=40)),
                ('verified', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=160)),
                ('project_type', models.CharField(choices=[('website', 'Website'), ('bot', 'Telegram bot'), ('app', 'App')], max_length=20)),
                ('asking_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Seller inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
