# Generated by Django 6.1 on 2026-09-12 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerinquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sellerinquiry',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='sellerinquiry',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_inquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
